### ISSUE TITLE
Enhancer center

### ISSUE THREAD

**Issue by Whu-gaochuan** [utsw-medical-center-banaszynski-lab/Martire-et-al-2019-Nature-Genetics#1]
Hi Martire：
I read your paper recently, this is a great job, but i have a question.
In this paper, like fig1e or Supplementary fig1i-1o, you test several histone modification on the enhancer center. I want to know the enhancer is WT enhancer or H3.3KO enhancer or both?
Thank you!

**Comment by aishwaryagogate** [comment]
Hello,
The enhancer file we used for those figures contains all WT mESC enhancers.
